DROP TABLE PACIENTE,
DROP TABLE ESPECIALIDADE,
DROP TABLE PACIENTE,
DROP TABLE CONSULTA,

CREATE TABLE PACIENTE(
    ID_PAC NUMBER(10) PRIMARY KEY,
    MOME VARCHAR2(240) NOT NULL,
    DATA_NASC DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    CPF CHAR(14) NULL,
    CONSTRAINT CK_GENERO_PAC CHECK (GENERO IN ('M', 'F')),
    CONSTRAINT UQ_PAC_CPF UNIQUE (CPF)
);
 
CREATE TABLE ESPECIALIDADE(
    ID_ESP NUMBER (10) PRIMARY KEY,
    NOME VARCHAR2 (120) NOT NULL,
    CONSTRAINT UQ_ESP_NOME UNIQUE (NOME),
);

CREATE TABLE MEDICO(
    CRM NUMBER (7) PRIMARY KEY,
    NOME VARCHAR2 (240) NOT NULL,
    DATA_NASC DATE NOT NULL,
    GENERO CHAR(1) NOT NULL,
    ID_ESP NUMBER(4) NOT NULL,
    CONSTRAINT CK_MED_GENERO CHECK (GENERO IN ('M', 'F')),
    CONSTRAINT FK_MED_ESP FOREIGN KEY (ID_ESP)
               REFERENCES ESPECIALIDADE (ID_ESP)
);

CREATE TABLE CONSULTA(
    CRM NUMBER(7),
    ID_PAC NUMBER(10),
    DTH_AGENDAMENTO DATE NOT NULL,
    TIPO CHAR(1) NOT NULL,
    STATUS CHAR(1) NOT NULL,
    OBSERVACAO VARCHAR(512) NULL,
    CONSTRAINT PK_CONSULTA
        PRIMARY KEY(CRM, ID_PAC, DTH_AGENDAMENTO),
    CONSTRAINT FK_CON_MED FOREIGN KEY (CRM)
        REFERENCES MEDICO (CRM),
    CONSTRAINT FK_CON_PAC FOREIGN KEY (ID_PAC)
        REFERENCES PACIENTE (ID_PAC),
    CONSTRAINT CK_CON_TIPO CHECK (TIPO IN ('C', 'R')),
    CONSTRAINT CK_CON_STATUS CHECK (STATUS IN ('A', 'C', 'R'))
);

INSERT INTO PACIENTE
VALUES('1001', 'João Pedro', TO_DATE('05/06/1998', 'DD/MM/YYYY'), 'M', NULL);

INSERT INTO PACIENTE (NOME, GENERO, ID_PAC, DATA_NASC)
VALUES( 'Ana Laura', 'F', 1002, TO_DATE('30/01/2003', 'DD/MM/YYYY'));