DROP SEQUENCE SEQ_PACIENTE;
DROP SEQUENCE SEQ_ESPECIALIDADE;

CREATE SEQUENCE SEQ_PACIENTE
START WITH 1003
INCREMENT BY 1
MAXVALUE 9999999999
NOCYCLE
NOCACHE;

CREATE SEQUENCE SEQ_ESPECIALIDADE
START WITH 1
INCREMENT BY 1
MAXVALUE 9999
NOCYCLE
NOCACHE;

INSERT INTO ESPECIALIDADE(ID_ESP, NOME) 
VALUES(SEQ_ESPECIALIDADE.NEXTVAL, 'CARDIOLOGISTA');
COMMIT;

INSERT INTO ESPECIALIDADE(ID_ESP, NOME) 
VALUES(SEQ_ESPECIALIDADE.NEXTVAL, 'NEUROLOGISTA');
COMMIT;

SELECT SEQ_ESPECIALIDADE.CURRVAL FROM DUAL;

INSERT INTO PACIENTE(ID_PAC, NOME, DATA_NASC, GENERO)
VALUES(SEQ_PACIENTE.NEXTVAL, 'Cláudia Aparecida Souza', TO_DATE('20/03/1998', 'DD/MM/YYYY'), 'F');

INSERT INTO MEDICO(CRM, NOME, DATA_NASC, GENERO, ID_ESP)
VALUES(10111, 'João Carlos Almeida', TO_DATE('01/06/1951', 'DD/MM/YYYY'), 'M', 1);

INSERT INTO CONSULTA (CRM, ID_PAC, DTH_AGENDAMENTO, TIPO, STATUS, OBSERVACAO)
VALUES(10111, 1001, TO_DATE('20/09/2025 13:52:00', 'DD/MM/YYYY HH24:MI:SS'), 'C', 'A', NULL);
COMMIT;

SELECT * FROM CONSULTA;
SELECT * FROM MEDICO;
SELECT * FROM PACIENTE;
SELECT * FROM ESPECIALIDADE;

SELECT ID_PAC, NOME, DATA_NASC, TO_CHAR(DATA)_NASC 'DD/YY/YYYY H24:MI:SS'

ROLLBACK;

