-- Visualizar a tabela JOBS
SELECT * FROM JOBS;

-- Visualizar a tabela EMPLOYEES (apenas algumas colunas)
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_ID 
FROM EMPLOYEES;

-- Exemplo de join antigo (usando vírgula e WHERE)
SELECT EMPLOYEE_ID, FIRST_NAME, JOB_TITLE
FROM EMPLOYEES, JOBS
WHERE EMPLOYEES.JOB_ID = JOBS.JOB_ID;

-- Usando alias e renomeando colunas
SELECT EMPLOYEE_ID AS "CÓDIGO", EMP.FIRST_NAME AS NOME, JOB_TITLE
FROM EMPLOYEES EMP, JOBS JOB
WHERE EMP.JOB_ID = JOB.JOB_ID;

-- Join EMPLOYEES x DEPARTMENTS (sintaxe corrigida)
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, DEP.DEPARTMENT_NAME
FROM EMPLOYEES EMP, DEPARTMENTS DEP
WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID;

-- Outer Join (sintaxe antiga do Oracle com (+))
SELECT EMP.FIRST_NAME, EMP.EMPLOYEE_ID, DEP.DEPARTMENT_NAME
FROM EMPLOYEES EMP, DEPARTMENTS DEP
WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID(+);

-- Join com 3 tabelas: EMPLOYEES, DEPARTMENTS, JOBS
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, DEP.DEPARTMENT_NAME, JOB.JOB_TITLE
FROM EMPLOYEES EMP, DEPARTMENTS DEP, JOBS JOB
WHERE EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID(+)
AND EMP.JOB_ID = JOB.JOB_ID;

-- RIGHT JOIN (traz todos os departamentos, mesmo sem empregados)
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, DEP.DEPARTMENT_NAME
FROM DEPARTMENTS DEP
RIGHT JOIN EMPLOYEES EMP
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID(+);

-- INNER JOIN (forma moderna e mais legível)
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, JOB.JOB_TITLE
FROM EMPLOYEES EMP
INNER JOIN JOBS JOB
ON EMP.JOB_ID = JOB.JOB_ID;

-- LEFT JOIN com duas tabelas e INNER JOIN com outra
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, DEP.DEPARTMENT_NAME, JOB.JOB_TITLE
FROM EMPLOYEES EMP
LEFT JOIN DEPARTMENTS DEP
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
INNER JOIN JOBS JOB
ON EMP.JOB_ID = JOB.JOB_ID;

-- Consulta final: EMPLOYEES + DEPARTMENTS + JOBS + LOCATIONS
SELECT EMP.EMPLOYEE_ID, EMP.FIRST_NAME, DEP.DEPARTMENT_NAME, JOB.JOB_TITLE, LOC.CITY
FROM EMPLOYEES EMP
LEFT JOIN DEPARTMENTS DEP
ON EMP.DEPARTMENT_ID = DEP.DEPARTMENT_ID
LEFT JOIN JOBS JOB
ON EMP.JOB_ID = JOB.JOB_ID
LEFT JOIN LOCATIONS LOC
ON DEP.LOCATION_ID = LOC.LOCATION_ID;